apiVersion: v2
type: application
name: ckan
description: CKAN backend for envidat.ch.
version: "0.1.1-chart"
appVersion: "local"
maintainers:
- email: samuel.woodcock@wsl.ch
  name: Sam Woodcock
home: https://github.com/EnviDat/ckan-container/tree/main/chart
icon: https://ckan.org/static/img/ckan.ico
dependencies:
  - name: postgresql
    version: 12.2.8
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: db.enabled
    alias: db
  - name: solr
    version: 7.2.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: solr.enabled
    alias: solr
  - name: redis
    version: 17.9.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
    alias: redis
