
.retag:
  stage: package
  image: docker.io/regclient/regctl:v0.3-alpine
  variables:
    GIT_STRATEGY: none
  before_script:
    - export REG_HOST=${INTERNAL_REG%/*}
    - >
      echo "{\"hosts\":{\"${REG_HOST}\":{\"tls\":\"enabled\",\"hostname\":
      \"${REG_HOST}\",\"user\":\"${IMAGE_REGISTRY_USER}\",\"pass\":
      \"${IMAGE_REGISTRY_PASS}\"}}}" >> /home/appuser/.regctl/config.json
  script:
    - >
      regctl --verbosity debug image copy
      "${IMAGE_NAME}-unverified" "${IMAGE_NAME}"
    - regctl --verbosity debug tag delete "${IMAGE_NAME}-unverified"

ckan-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${CKAN_IMAGE}

proxy-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${PROXY_IMAGE}

db-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${DB_IMAGE}

solr-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${SOLR_IMAGE}

solr-init-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${SOLR_INIT_IMAGE}
