stages:
  - build
  - scan
  - package
  - deploy
  - release

variables:
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: always
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: always
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

set-vars:
  stage: .pre
  image: docker.io/alpine:3.15
  before_script:
    - >
      apk add jq yq --no-cache
      --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
  script:
    - cat .env >> build.env
    - source build.env
    - echo "NAMESPACE=ckan" >> build.env
    - echo "APP_NAME=ckan-${CI_COMMIT_REF_NAME}" >> build.env
    - echo CHART_VERSION=$(yq '.version' chart/Chart.yaml) >> build.env
    - "echo CKAN_IMAGE=${INTERNAL_REG}/ckan-container/ckan:\
      ${CKAN_VERSION}-${CI_COMMIT_REF_NAME} >> build.env"
    - "echo PROXY_IMAGE=${INTERNAL_REG}/ckan-container/proxy:\
      ${NGINX_IMG_TAG}-${CI_COMMIT_REF_NAME} >> build.env"
    - "echo DB_IMAGE=${INTERNAL_REG}/ckan-container/db:\
      ${POSTGRES_IMG_TAG}-${CI_COMMIT_REF_NAME} >> build.env"
    - "echo SOLR_IMAGE=${INTERNAL_REG}/ckan-container/solr:\
      ${SOLR_IMG_TAG}-${CI_COMMIT_REF_NAME} >> build.env"
    - "echo SOLR_INIT_IMAGE=${INTERNAL_REG}/ckan-container/init-solr:\
      ${SOLR_IMG_TAG}-${CI_COMMIT_REF_NAME} >> build.env"
  artifacts:
    reports:
      dotenv: build.env

.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"${INTERNAL_REG}\":{\"auth\":\"$(printf
      "%s:%s" "${IMAGE_REGISTRY_USER}" "${IMAGE_REGISTRY_PASS}"
      | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor
      --force
      --context "${CONTEXT_DIR}"
      --dockerfile "${CONTEXT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}-unverified"
      --build-arg MAINTAINER="${MAINTAINER}"
      --build-arg EXTERNAL_REG="${EXTERNAL_REG}"
      --build-arg INTERNAL_REG="${INTERNAL_REG}"
      --build-arg PYTHON_IMG_TAG="${PYTHON_IMG_TAG}"
      --build-arg CKAN_VERSION="${CKAN_VERSION}"
      --build-arg POSTGRES_IMG_TAG="${POSTGRES_IMG_TAG}"
      --build-arg SOLR_IMG_TAG="${SOLR_IMG_TAG}"
      --build-arg NGINX_IMG_TAG="${NGINX_IMG_TAG}"
      --build-arg NGINX_CONFIG_NAME="${NGINX_CONFIG_NAME}"

ckan-build:
  extends:
    - .build
  variables:
    IMAGE_NAME: ${CKAN_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}"

proxy-build:
  extends:
    - .build
  cache:
    key: nginx-config
    paths:
      - nginx/conf.d/ckan.conf
    policy: pull
  variables:
    IMAGE_NAME: ${PROXY_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}/nginx"

db-build:
  extends:
    - .build
  variables:
    IMAGE_NAME: ${DB_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}/postgresql"

solr-build:
  extends:
    - .build
  variables:
    IMAGE_NAME: ${SOLR_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}/solr"

solr-init-build:
  extends:
    - .build
  variables:
    IMAGE_NAME: ${SOLR_INIT_IMAGE}
    CONTEXT_DIR: "${CI_PROJECT_DIR}/init_solr"

.scan:
  stage: scan
  image:
    name: docker.io/aquasec/trivy:0.23.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  script:
    - trivy --version
    - time trivy image --clear-cache
    - time trivy --cache-dir .trivycache/ image --download-db-only --no-progress
    # Create report artifact
    - >
      time trivy --cache-dir .trivycache/ image --exit-code 0 --ignore-unfixed
      --no-progress --format template --template "@/contrib/gitlab.tpl"
      --output "$CI_PROJECT_DIR/$SHORT_NAME-imgscan.json"
      "${IMAGE_NAME}-unverified"
    # Print full report
    - >
      time trivy --cache-dir .trivycache/ image --exit-code 0 --ignore-unfixed
      --no-progress "${IMAGE_NAME}"-unverified
    # Fail on critical vulnerabilities
    - >
      time trivy --cache-dir .trivycache/ image --exit-code 1 --ignore-unfixed
      --severity CRITICAL --no-progress "${IMAGE_NAME}"-unverified
  cache:
    key: trivy-cache
    paths:
      - .trivycache/
    policy: pull-push
  artifacts:
    when: always
    reports:
      container_scanning: $SHORT_NAME-imgscan.json

ckan-scan:
  extends:
    - .scan
  variables:
    IMAGE_NAME: ${CKAN_IMAGE}
    SHORT_NAME: "ckan"
  allow_failure: true

proxy-scan:
  extends:
    - .scan
  variables:
    IMAGE_NAME: ${PROXY_IMAGE}
    SHORT_NAME: "proxy"

db-scan:
  extends:
    - .scan
  variables:
    IMAGE_NAME: ${DB_IMAGE}
    SHORT_NAME: "postgresql"

solr-scan:
  extends:
    - .scan
  variables:
    IMAGE_NAME: ${SOLR_IMAGE}
    SHORT_NAME: "solr"
  allow_failure: true

solr-init-scan:
  extends:
    - .scan
  variables:
    IMAGE_NAME: ${SOLR_INIT_IMAGE}
    SHORT_NAME: "init_solr"

.retag:
  stage: package
  image: docker.io/regclient/regctl:v0.3-alpine
  variables:
    GIT_STRATEGY: none
  before_script:
    - export REG_HOST=${INTERNAL_REG%/*}
    - >
      echo "{\"hosts\":{\"${REG_HOST}\":{\"tls\":\"enabled\",\"hostname\":
      \"${REG_HOST}\",\"user\":\"${IMAGE_REGISTRY_USER}\",\"pass\":
      \"${IMAGE_REGISTRY_PASS}\"}}}" >> /home/appuser/.regctl/config.json
  script:
    - >
      regctl --verbosity debug image copy
      "${IMAGE_NAME}-unverified" "${IMAGE_NAME}"
    - regctl --verbosity debug tag delete "${IMAGE_NAME}-unverified"

ckan-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${CKAN_IMAGE}

proxy-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${PROXY_IMAGE}

db-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${DB_IMAGE}

solr-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${SOLR_IMAGE}

solr-init-retag:
  extends:
    - .retag
  variables:
    IMAGE_NAME: ${SOLR_INIT_IMAGE}

.helm:
  stage: deploy
  image:
    name: docker.io/alpine/helm:3.8.0
    entrypoint: [""]
  before_script:
    - mkdir -p /root/.config/helm/registry
    - >
      echo "{\"auths\":{\"${INTERNAL_REG}\":{\"auth\":\"$(printf "%s:%s"
      "${IMAGE_REGISTRY_USER}" "${IMAGE_REGISTRY_PASS}" | base64
      | tr -d '\n')\"}}}" > /root/.config/helm/registry/config.json

create-helm-chart:
  extends:
    - .helm
  stage: package
  rules:
    - if: $CI_COMMIT_REF_NAME != "main"
      when: never
    - when: always
  script:
    - >
      apk add yq --no-cache
      --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    - helm dependencies build chart
    - yq -i '.appVersion = strenv(CKAN_VERSION)' chart/Chart.yaml
    - helm package chart
    - CHART_VER=$(yq '.version' chart/Chart.yaml)
    - helm push "ckan-${CHART_VER}.tgz" oci://registry-gitlab.wsl.ch/envidat/ckan-container

# helm-deploy:
#   extends:
#     - .helm
#   rules:
#     - if: $CI_COMMIT_REF_NAME == "main"
#       when: never
#     - when: on_success
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - >
#       helm upgrade --install "${APP_NAME}"
#       oci://registry-gitlab.wsl.ch/envidat/ckan-container/ckan
#       --namespace "${NAMESPACE}" --create-namespace
#       --version "${CHART_VERSION}"
#       --set image.tag="${CKAN_VERSION}-${CI_COMMIT_REF_NAME}"
#       --set proxy.image.tag="${NGINX_IMG_TAG}-${CI_COMMIT_REF_NAME}"
#       --set image.pullPolicy="Always"
#       --set configIniSecret="${APP_NAME}-config-ini"
#       --set authCookieName="${APP_NAME//-/_}"
#       --set extraEnvFrom[0].secretRef.name="solr-${APP_NAME}-vars"
#       --set ingress.hosts[0].host="${APP_NAME}.envidat.ch"
#       --set ingress.hosts[0].paths[0].path="/"
#       --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"
#       --set ingress.tls[0].secretName="envidat-star"
#       --set ingress.tls[0].hosts[0]="${APP_NAME}.envidat.ch"
#       --set db.auth.existingSecret="db-${APP_NAME}-creds"
#       --set db.primary.resources.requests.cpu="100m"
#       --set db.primary.resources.requests.memory="100Mi"
#       --set db.syncData.restoreDbSecret="db-${APP_NAME}-vars"
#       --set solr.image.tag="${SOLR_IMG_TAG}-${CI_COMMIT_REF_NAME}"
#       --set solr.ingress.hostname="solr-${CI_COMMIT_REF_NAME}.envidat.ch"
#       --set solr.passwordInitCredsSecret="solr-${APP_NAME}-vars"
#       --set autoscaling.enabled=false

# helm-deploy-prod:
#   extends:
#     - .helm
#   rules:
#     - if: $CI_COMMIT_REF_NAME != "main"
#       when: never
#     - when: on_success
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - >
#       helm upgrade --install "${APP_NAME}"
#       oci://registry-gitlab.wsl.ch/envidat/ckan-container/ckan
#       --namespace "${NAMESPACE}" --create-namespace
#       --version "${CHART_VERSION}"
#       --set image.tag="${CKAN_VERSION}-${CI_COMMIT_REF_NAME}"
#       --set proxy.image.tag="${NGINX_IMG_TAG}-${CI_COMMIT_REF_NAME}"

build-binary:
  stage: release
  image: docker.io/debian:bookworm
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apt update && apt install -y curl
    - curl -LO https://github.com/ajdiaz/bashc/releases/download/5.2.15/bashc
    - chmod +x bashc
  script:
    - ./bashc scripts/envidat-in-a-box.sh envidat
  after_script:
    - echo "BIN_JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - envidat
    expire_in: never
    reports:
      dotenv: job.env

release-binary:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build-binary
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    - echo "Using artifact from job $BIN_JOB_ID"
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: envidat-in-a-box
          url: $CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$BIN_JOB_ID/artifacts/raw/envidat
