version: "3"

volumes:
  ckan_storage:
  pg_data:
  solr_data:

secrets:
  ckan_config:
    file: ./${CKAN_CONFIG_FILE:-/dev/null}
  db_init_pass:
    file: ./${CKAN_DB_INIT_PASS_FILE:-/dev/null}
  db_env_secret:
    file: ./${CKAN_DB_SECRET_FILE:-/dev/null}
  solr_creds:
    file: ./${CKAN_SOLR_CREDS_FILE:-/dev/null}

networks:
  ckan-internal:
    external: true

services:
  ckan:
    container_name: ckan
    image: "${INTERNAL_REG}/ckan:${CKAN_VERSION}"
    build:
      context: .
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - CKAN_VERSION=${CKAN_VERSION}
        - MAINTAINER=${MAINTAINER}
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "8989:5000"
    env_file:
      - .env
    secrets:
      - ckan_config
    volumes:
      - ckan_storage:/var/lib/ckan
    networks:
      - ckan-internal

  db:
    container_name: ckan_db
    image: "${INTERNAL_REG}/ckan-db:latest"
    build:
      context: ./postgresql
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - MAINTAINER=${MAINTAINER}
    environment:
      - PGDATA=/var/lib/postgresql/data/db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_init_pass
    secrets:
      - db_init_pass
      - db_env_secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ckan-internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$CKAN_DB_USER"]

  solr:
    container_name: ckan_solr
    image: "${INTERNAL_REG}/ckan-solr:latest"
    build:
      context: ./solr
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - MAINTAINER=${MAINTAINER}
    volumes:
      - solr_data:/opt/solr/server/solr
    networks:
      - ckan-internal

  init-solr:
    container_name: ckan_init_solr
    image: "${INTERNAL_REG}/ckan-init-solr:latest"
    build:
      context: ./init_solr
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - MAINTAINER=${MAINTAINER}
    secrets:
      - solr_creds
    networks:
      - ckan-internal
    depends_on:
      - solr

  redis:
    container_name: ckan_redis
    image: redis:6.2
    networks:
      - ckan-internal
