version: "3"

volumes:
  ckan_dev_storage:
  ckan_dev_translations:

networks:
  ckan-internal:
    name: ckan-dev

services:
  ckan:
    container_name: ckan_dev
    #image: "${INTERNAL_REG}/ckan-container/ckan:${CKAN_VERSION}-dev"
    build:
      context: ./
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - INTERNAL_REG=${INTERNAL_REG}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - CKAN_VERSION=${CKAN_VERSION}
        - MAINTAINER=${MAINTAINER}
      dockerfile: ./Dockerfile
    depends_on:
      - solr
      - redis
    environment:
      CKAN_INI: "/opt/ckan/ckan.ini"
    #entrypoint: /bin/sh  # Override to run a shell instead of the application
    #tty: true  # Keeps the container running for interactive shell access
    volumes:
      - ckan_dev_storage:/opt/ckan/data
      - ./config/ckan.ini:/opt/ckan/ckan.ini
      - ckan_dev_translations:/usr/lib/ckan/.local/lib/python${PYTHON_IMG_TAG}/site-packages/ckan/public/base/i18n
    networks:
      - ckan-internal
    restart: unless-stopped

  proxy:
    container_name: ckan_dev_proxy
    image: "${INTERNAL_REG}/ckan-container/proxy:${NGINX_IMG_TAG}-main"
    depends_on:
      - ckan
    environment:
      - CKAN_HOST=ckan:5000
      - AUTH_COOKIE_NAME=envidat
    ports:
      - "8081:80"
    networks:
      - ckan-internal
    restart: unless-stopped

  #db:
  #  container_name: ckan_dev_db
  #  image: "${INTERNAL_REG}/ckan-container/db:${POSTGRES_IMG_TAG}-dev"
  #  env_file:
  #    - .db.env
  #  networks:
  #    - ckan-internal
  #  healthcheck:
  #    test: ["CMD", "pg_isready", "-U", "postgres"]
  #  restart: unless-stopped

  solr:
    container_name: ckan_dev_solr
    image: "${INTERNAL_REG}/ckan-container/solr:${SOLR_IMG_TAG}-dev"
    networks:
      - ckan-internal
    restart: unless-stopped

  init-solr:
    container_name: ckan_dev_init_solr
    image: "${INTERNAL_REG}/ckan-container/init-solr:${SOLR_IMG_TAG}-dev"
    env_file:
      - .solr.env
    environment:
      SOLR_HOST: http://solr:8983
    networks:
      - ckan-internal
    depends_on:
      - solr

  redis:
    container_name: ckan_dev_redis
    image: redis:${REDIS_IMG_TAG}
    networks:
      - ckan-internal
    restart: unless-stopped
