version: "3"

volumes:
  ckan_storage:
  ckan_translations:
  pg_data:
  solr_data:

networks:
  ckan-internal:
    name: ckan-local
  micro-net:
    external: true

services:
  ckan:
    container_name: ckan
    image: "${INTERNAL_REG}/ckan-container/ckan:2.9-backup"
    build:
      context: .
      target: debug
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - INTERNAL_REG=${INTERNAL_REG}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - CKAN_VERSION=${CKAN_VERSION}
        - MAINTAINER=${MAINTAINER}
    extra_hosts:
      mail.wsl.ch: 10.30.1.224
    depends_on:
      - solr
      - redis
    environment:
      CKAN_INI: "/opt/ckan/ckan.ini"
    volumes:
      - ckan_storage:/opt/ckan/data
      - ./config/ckan.ini:/opt/ckan/ckan.ini 
      - ckan_translations:/usr/lib/ckan/.local/lib/python3.10/site-packages/ckan/public/base/i18n
    networks:
      - ckan-internal
    restart: unless-stopped
   
  doi_api:
    container_name: doi_api_dev
    image: "${INTERNAL_REG}/doi-publishing-api:${APP_VERSION}-dev"
    env_file:
      - .doi.env
      #- .db.env
      #- secret/runtime.env
    environment:
      IS_DOCKER: "True"
    networks:
      - micro-net
    restart: unless-stopped

  proxy:
    container_name: ckan_proxy
    #image: "${INTERNAL_REG}/ckan-container/proxy:${NGINX_IMG_TAG}-main"
    build:
      context: ./nginx
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - NGINX_IMG_TAG=${NGINX_IMG_TAG}
        - MAINTAINER=${MAINTAINER}
      dockerfile: ./Dockerfile
    depends_on:
      - ckan
    environment:
      - AUTH_COOKIE_NAME=envidat
      - CKAN_HOST=ckan:5000
      - DOI_HOST=doi_api:8000
      - CONVERTERS_HOST=converters_api:8000
    env_file:
      - .env
      - .doi.env
    ports:
      - "8989:80"
    networks:
      - ckan-internal
      - micro-net
    restart: unless-stopped

  solr:
    container_name: ckan_dev_solr
    image: "${INTERNAL_REG}/ckan-container/solr:${SOLR_IMG_TAG}-dev"
    networks:
      - ckan-internal
    restart: unless-stopped

  init-solr:
    container_name: ckan_dev_init_solr
    image: "${INTERNAL_REG}/ckan-container/init-solr:${SOLR_IMG_TAG}-dev"
    env_file:
      - .solr.env
    environment:
      SOLR_HOST: http://solr:8983
    networks:
      - ckan-internal
    depends_on:
      - solr

  redis:
    container_name: ckan_redis
    image: redis:${REDIS_IMG_TAG}
    networks:
      - ckan-internal
    restart: unless-stopped

