version: "3"

volumes:
  ckan_storage:
  pg_data:
  solr_data:

networks:
  ckan-internal:
    external: true

services:
  ckan:
    container_name: ckan
    image: "${INTERNAL_REG}/ckan:${CKAN_VERSION}-main"
    build:
      context: .
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - CKAN_VERSION=${CKAN_VERSION}
        - MAINTAINER=${MAINTAINER}
    extra_hosts:
      notes.wsl.ch: 10.30.1.65
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "8989:5000"
    env_file:
      - .env
    volumes:
      - ckan_storage:/opt/ckan/data
      - ./ckan.ini:/home/ckan/ckan.ini
    networks:
      - ckan-internal

  db:
    container_name: ckan_db
    image: "${INTERNAL_REG}/ckan-db:${POSTGRES_VERSION}-${POSTGIS_VERSION}-main"
    build:
      context: ./postgresql
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - POSTGIS_VERSION=${POSTGIS_VERSION}
        - MAINTAINER=${MAINTAINER}
    environment:
      - POSTGRES_PASSWORD=ai4ncF6GpHokPaNmW25UftzMjM7hrC
      - PGDATA=/var/lib/postgresql/data/db
    env_file:
      - .db.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /etc/hosts:/etc/hosts:ro
    networks:
      - ckan-internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - "25432:5432"

  solr:
    container_name: ckan_solr
    image: "${INTERNAL_REG}/ckan-solr:${SOLR_VERSION}-main"
    build:
      context: ./solr
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - SOLR_VERSION=${SOLR_VERSION}
        - MAINTAINER=${MAINTAINER}
    volumes:
      - solr_data:/opt/solr/server/solr
    networks:
      - ckan-internal

  init-solr:
    container_name: ckan_init_solr
    image: "${INTERNAL_REG}/ckan-init-solr:${SOLR_VERSION}-main"
    build:
      context: ./init_solr
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - MAINTAINER=${MAINTAINER}
    environment:
      SOLR_HOST: http://solr:8983
      SOLR_ADMIN_PASS: 4hAYTQkUD6REA3futeKsvUjvK9wETG
      SOLR_CKAN_PASS: MPnJRcGVGurpJF3kWq2eFNDEr3cXv6
    networks:
      - ckan-internal
    depends_on:
      - solr

  redis:
    container_name: ckan_redis
    image: redis:${REDIS_VERSION}
    networks:
      - ckan-internal
