version: "3"

volumes:
  ckan_storage:
  ckan_translations:
  solr_data:

networks:
  ckan-microservices:
    name: envidat
  ckan-internal:
    name: ckan-2.9

services:
  ckan:
    container_name: ckan_2.9
    image: "${INTERNAL_REG}/ckan-container/ckan:${CKAN_VERSION}-staging"
    depends_on:
      - solr
      - redis
    environment:
      CKAN_INI: "/opt/ckan/ckan.ini"
    volumes:
      - ckan_storage:/opt/ckan/data
      - $HOME/config/ckan/staging.ini:/opt/ckan/ckan.ini
      - ckan_translations:/usr/lib/ckan/.local/lib/python3.10/site-packages/ckan/public/base/i18n
    networks:
      - ckan-internal
      - ckan-microservices
    restart: unless-stopped

  proxy:
    container_name: ckan_2.9_proxy
    image: "${INTERNAL_REG}/ckan-container/proxy:${NGINX_IMG_TAG}-staging"
    depends_on:
      - ckan
    environment:
      - CKAN_HOST=ckan:5000
      - AUTH_COOKIE_NAME=envidat
    ports:
      - "8081:80"
    networks:
      - ckan-internal
    restart: unless-stopped

  solr:
    container_name: ckan_2.9_solr
    image: "${INTERNAL_REG}/ckan-container/solr:${SOLR_IMG_TAG}-staging"
    volumes:
      - solr_data:/var/solr/data
    networks:
      - ckan-internal
    ports:
      - "8090:8983"
    restart: unless-stopped

  init-solr:
    container_name: ckan_2.9_init_solr
    image: "${INTERNAL_REG}/ckan-container/init-solr:${SOLR_IMG_TAG}-staging"
    env_file:
      - .solr.env
    environment:
      SOLR_HOST: http://solr:8983
    networks:
      - ckan-internal
    depends_on:
      - solr

  redis:
    container_name: ckan_2.9_redis
    image: redis:${REDIS_IMG_TAG}
    networks:
      - ckan-internal
    restart: unless-stopped

