{{- if .Values.solr.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-solr-init
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: solr-init-passwords
        image: "{{ .Values.image.repository }}-init-solr:{{ .Values.solr.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ .Values.solr.passwordInitCredsSecret }}
      restartPolicy: Never
      activeDeadlineSeconds: 180
  backoffLimit: 1
{{- end }}
