scheming_version: 2
dataset_type: dataset
about: The default CKAN dataset schema plus additional EnviDat fields
about_url: http://github.com/ckan/ckanext-scheming

dataset_fields:
  - field_name: title
    label: Title
    validators: "if_empty_same_as(name) unicode_safe"

  - field_name: name
    label: URL
    validators: "not_empty unicode_safe name_validator package_name_validator envidat_shortname_validator"

  - field_name: doi
    label: DOI

  - field_name: publication_state
    label: Publication State
    validators: "scheming_choices"
    choices:
      - value: ""
        label: ""
      - value: "reserved"
        label: "Reserved"
      - value: "pub_requested"
        label: "Publication Requested"
      - value: "pub_pending"
        label: "Publication Pending"
      - value: "approved"
        label: "Approved"
      - value: "published"
        label: "Published"

  - field_name: owner_org
    label: Organization
    validators: "owner_org_validator unicode_safe"

  - field_name: notes
    label: Description
    validators: "scheming_required envidat_minimum_description_length"
    required: true

  - field_name: funding
    label: Funding Information
    validators: "scheming_required composite_repeating_group2json"
    required: true
    repeating_label: "Funder no."
    repeating_subfields:
      - field_name: institution
        label: Name
        required: true
      - field_name: institution_url
        label: "Link to Funding Agency"
      - field_name: grant_number
        label: "Grant Number"

  - field_name: related_datasets
    label: Related Datasets

  - field_name: related_publications
    label: Related Publications

  - field_name: tag_string
    label: Keywords
    required: true

  - field_name: author
    label: Authors
    required: true
    validators: "scheming_required composite_repeating_group2json envidat_reorder"
    repeating_label: "Author no."
    repeating_subfields:
      - field_name: email
        label: Email
        required: true
      - field_name: autocomplete
        label: Autocomplete
      - field_name: identifier
        label: ORCID
      - field_name: given_name
        label: Given Name
      - field_name: name
        label: Family Name
        required: true
      - field_name: identifier_scheme
        label: Scheme
        default: "orcid"
        choices:
          - value: "orcid"
            label: "ORCID"
          - value: "isni"
            label: "ISNI"
          - value: "rid"
            label: "ResearcherID"
          - value: "rgate"
            label: "ResearchGate"
      - field_name: affiliation
        label: Affiliation
        required: true
      - field_name: affiliation_02
        label: Additional Affiliation
      - field_name: affiliation_03
        label: Additional Affiliation
      - field_name: data_credit
        label: DataCredit
        preset: multiple_checkbox
        choices:
          - value: "collection"
            label: "Collection"
          - value: "validation"
            label: "Validation"
          - value: "curation"
            label: "Curation"
          - value: "software"
            label: "Software"
          - value: "publication"
            label: "Publication"
          - value: "supervision"
            label: "Supervision"
      - field_name: order
        label: Order

  - field_name: maintainer
    label: Contact Person
    validators: "composite_group2json"
    required: true
    repeating_label: "Contact"
    repeating_subfields:
      - field_name: copy-from-author
        label: Name
      - field_name: given_name
        label: Given Name
      - field_name: name
        label: Family Name
        required: true
      - field_name: email
        label: Email
        required: true
      - field_name: affiliation
        label: Affiliation
      - field_name: identifier
        label: ORCID
      - field_name: identifier_scheme
        label: Scheme
        default: "orcid"
        choices:
          - value: "orcid"
            label: "ORCID"
          - value: "isni"
            label: "ISNI"
          - value: "rid"
            label: "ResearcherID"
          - value: "rgate"
            label: "ResearchGate"

  - field_name: subtitle
    label: Subtitles
    validators: "composite_repeating_group2json"
    repeating_label: "Subtitles"
    repeating_subfields:
      - field_name: subtitle
        label: Subtitle
        required: true
      - field_name: type
        label: Type
        choices:
          - value: "alternative_title"
            label: "Alternative Title"
          - value: "subtitle"
            label: "Subtitle"
          - value: "translated_title"
            label: "Translated Title"
          - value: "other"
            label: "Other"
      - field_name: language
        label: Language
        preset: select
        choices:
          - value: "en"
            label: "English"
          - value: "de"
            label: "German"
          - value: "fr"
            label: "French"
          - value: "it"
            label: "Italian"
          - value: "ro"
            label: "Romansh"

  - field_name: publication
    label: Publication
    validators: "composite_group2json"
    required: true
    repeating_label: "Publication"
    repeating_subfields:
      - field_name: publisher
        label: Publisher
        default: "EnviDat"
      - field_name: publication_year
        label: Year
        required: true
        default: "composite_current_year"

  - field_name: date
    label: Dates
    validators: "composite_repeating_group2json"
    required: true
    repeating_label: "Dates"
    repeating_subfields:
      - field_name: date_type
        label: Type
        required: true
        choices:
          - value: "collected"
            label: "Collected"
          - value: "created"
            label: "Created"
      - field_name: date
        label: Date
        preset: date
        required: true
      - field_name: end_date
        label: End Date
        preset: date
        required: false

  - field_name: license_id
    label: Content License
    required: true

  - field_name: version
    label: Version
    validators: "ignore_missing unicode_safe package_version_validator"
    default: "1.0"
    required: true

  - field_name: resource_type
    label: Type
    default: "Dataset"
    validators: "envidat_copy_type_general"

  - field_name: resource_type_general
    label: General Type
    required: true
    default: "dataset"
    validators: "scheming_required scheming_choices"
    choices:
      - value: "dataset"
        label: "Dataset"
      - value: "datapaper"
        label: "DataPaper"
      - value: "software"
        label: "Software"

  - field_name: language
    label: Language
    default: "en"
    validators: "scheming_required scheming_choices"
    choices:
      - value: "en"
        label: "English"
      - value: "de"
        label: "German"
      - value: "fr"
        label: "French"
      - value: "it"
        label: "Italian"
      - value: "ro"
        label: "Romansh"

  - field_name: spatial_info
    label: Location
    default: "Switzerland"

  - field_name: spatial
    default: '{"type": "Polygon", "coordinates": [[[5.95587, 45.81802],[5.95587, 47.80838],[10.49203, 47.80838],[10.49203, 45.81802],[5.95587, 45.81802]]]}'
    required: true
    label: "Spatial Extent"

resource_fields:
  - field_name: name
    label: Name
    validators: "not_empty unicode_safe"

  - field_name: description
    label: Description

  - field_name: url
    label: URL

  - field_name: format
    label: Format

  - field_name: resource_size
    label: Size
    validators: "composite_group2json"
    repeating_label: "Size"
    repeating_subfields:
      - field_name: size_value
        label: Size
      - field_name: size_units
        label: Unit
        default: "kb"
        choices:
          - value: "kb"
            label: "KB"
          - value: "mb"
            label: "MB"
          - value: "gb"
            label: "GB"
          - value: "tb"
            label: "TB"

  - field_name: doi
    label: DOI
    validators: "scheming_required"

  - field_name: restricted
    label: Access Restriction
    validators: "composite_group2json restricted_username_from_mail"
    repeating_label: "Restricted"
    repeating_subfields:
      - field_name: level
        label: Level
        required: true
        choices:
          - value: "public"
            label: "Public"
          - value: "same_organization"
            label: "Restricted to Same Organization Members"
      - field_name: allowed_users
        label: Allowed Users
      - field_name: shared_secret
        label: Shared Secret

  - field_name: publication_state
    label: Publication State
    validators: "scheming_required scheming_choices"
    choices:
      - value: ""
        label: ""
      - value: "published"
        label: "Published"
