#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL
    CREATE ROLE $CKAN_DB_USER WITH
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE
        INHERIT
        LOGIN
        NOREPLICATION
        NOBYPASSRLS
        PASSWORD '$CKAN_DB_PASS';
    CREATE DATABASE $CKAN_DB_NAME WITH OWNER=$CKAN_DB_USER;
    CREATE DATABASE $CKAN_DOI_DB_NAME WITH OWNER=$CKAN_DB_USER;
EOSQL